version: '3.8'

services:
  gestor_catalogos_api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: gestor_catalogos_api
    restart: always  # <--- ESSA LINHA AQUI
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data

  gestor_tarefas_ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gestor_catalogos_ui
    restart: always  # <--- E ESSA LINHA AQUI
    ports:
      - "80:80"
    depends_on:
      - gestor_catalogos_api

volumes:
  sqlite_data: